"""initial schema

Revision ID: 084cbf687504
Revises: 
Create Date: 2026-07-19 07:50:29.035124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '084cbf687504'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_series',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('exercise_types',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('default_instruction', sa.Text(), nullable=False),
    sa.Column('has_passage', sa.Boolean(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('grammar_topics',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('passage_length_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grade_min', sa.Integer(), nullable=False),
    sa.Column('grade_max', sa.Integer(), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=False),
    sa.Column('max_words', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('proficiency_levels',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code'),
    sa.UniqueConstraint('rank')
    )
    op.create_table('school_stages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'TEACHER', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('cambridge_certificates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('cefr_level_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['cefr_level_id'], ['proficiency_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('grades',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('school_stage_id', sa.UUID(), nullable=False),
    sa.Column('suggested_level_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['school_stage_id'], ['school_stages.id'], ),
    sa.ForeignKeyConstraint(['suggested_level_id'], ['proficiency_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('number')
    )
    op.create_table('grammar_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['grammar_topics.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('topic_id', 'order_no', name='uq_grammar_groups_topic_order')
    )
    op.create_table('sentence_length_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_stage_id', sa.UUID(), nullable=False),
    sa.Column('min_words', sa.Integer(), nullable=False),
    sa.Column('max_words', sa.Integer(), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['school_stage_id'], ['school_stages.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('school_stage_id')
    )
    op.create_table('grammar_points',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('min_level_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['grammar_groups.id'], ),
    sa.ForeignKeyConstraint(['min_level_id'], ['proficiency_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'order_no', name='uq_grammar_points_group_order')
    )
    op.create_table('units',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('book_series_id', sa.UUID(), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['book_series_id'], ['book_series.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('grade_id', 'order_no', name='uq_units_grade_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('units')
    op.drop_table('grammar_points')
    op.drop_table('sentence_length_rules')
    op.drop_table('grammar_groups')
    op.drop_table('grades')
    op.drop_table('cambridge_certificates')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('school_stages')
    op.drop_table('proficiency_levels')
    op.drop_table('passage_length_rules')
    op.drop_table('grammar_topics')
    op.drop_table('exercise_types')
    op.drop_table('book_series')
    op.execute('DROP TYPE IF EXISTS user_role')
    # ### end Alembic commands ###
