"""add exam block parts

Revision ID: 2d5cd6b86625
Revises: c2e6a1f9d3b4
Create Date: 2026-07-20 09:54:42.859489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d5cd6b86625'
down_revision: Union[str, None] = 'c2e6a1f9d3b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_block_parts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['block_id'], ['exam_blocks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'order_no', name='uq_block_part_order')
    )
    op.add_column('questions', sa.Column('part_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'questions', 'exam_block_parts', ['part_id'], ['id'])
    # ### end Alembic commands ###
    # Bỏ qua thay đổi index/FK trên knowledge_chunks: autogenerate báo sai lệch do
    # SQLAlchemy không phản chiếu ondelete=CASCADE hiện có trong DB, không liên quan
    # tới feature này — xem c2e6a1f9d3b4_add_knowledge_base.py cho định nghĩa gốc.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'part_id')
    op.drop_table('exam_block_parts')
    # ### end Alembic commands ###
