"""exam core tables

Revision ID: f1af42b1bbf5
Revises: 084cbf687504
Create Date: 2026-07-19 08:25:36.103966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1af42b1bbf5'
down_revision: Union[str, None] = '084cbf687504'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exams',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('grade_id', sa.UUID(), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('source_type', sa.Enum('GLOBAL_SUCCESS', 'COMMON_KNOWLEDGE', 'CAMBRIDGE', name='exam_source_type'), nullable=False),
    sa.Column('unit_id', sa.UUID(), nullable=True),
    sa.Column('grammar_topic_id', sa.UUID(), nullable=True),
    sa.Column('cambridge_certificate_id', sa.UUID(), nullable=True),
    sa.Column('extra_prompt', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'READY', name='exam_status'), nullable=False),
    sa.Column('export_mode', sa.Enum('PLAIN', 'ANSWER_KEY', name='exam_export_mode'), nullable=True),
    sa.Column('variant_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cambridge_certificate_id'], ['cambridge_certificates.id'], ),
    sa.ForeignKeyConstraint(['grade_id'], ['grades.id'], ),
    sa.ForeignKeyConstraint(['grammar_topic_id'], ['grammar_topics.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['proficiency_levels.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['unit_id'], ['units.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exam_blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('exercise_type_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('instruction', sa.Text(), nullable=True),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('points', sa.Numeric(precision=4, scale=1), nullable=False),
    sa.Column('difficulty', sa.Enum('NHAN_BIET', 'THONG_HIEU', 'VAN_DUNG', 'HON_HOP', name='exam_block_difficulty'), nullable=False),
    sa.Column('level_override_id', sa.UUID(), nullable=True),
    sa.Column('shuffle_questions', sa.Boolean(), nullable=False),
    sa.Column('shuffle_answers', sa.Boolean(), nullable=False),
    sa.Column('prompt_override', sa.Text(), nullable=True),
    sa.Column('passage_word_target', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['exercise_type_id'], ['exercise_types.id'], ),
    sa.ForeignKeyConstraint(['level_override_id'], ['proficiency_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'order_no', name='uq_exam_block_order')
    )
    op.create_table('exam_grammar_selections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('grammar_point_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['grammar_point_id'], ['grammar_points.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'grammar_point_id', name='uq_exam_grammar_point')
    )
    op.create_table('exam_variants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('exam_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=5), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('question_order', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'code', name='uq_exam_variant_code')
    )
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('block_id', sa.UUID(), nullable=False),
    sa.Column('order_no', sa.Integer(), nullable=False),
    sa.Column('prompt_text', sa.Text(), nullable=False),
    sa.Column('passage_text', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('target_knowledge', sa.String(length=255), nullable=False),
    sa.Column('level_id', sa.UUID(), nullable=False),
    sa.Column('source_ref', sa.String(length=255), nullable=False),
    sa.Column('warnings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_approved', sa.Boolean(), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('is_in_bank', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['exam_blocks.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['proficiency_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('block_id', 'order_no', name='uq_question_block_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questions')
    op.drop_table('exam_variants')
    op.drop_table('exam_grammar_selections')
    op.drop_table('exam_blocks')
    op.drop_table('exams')
    # ### end Alembic commands ###
