"""add grammar point to knowledge document

Revision ID: fb9639cd5a3a
Revises: 2d5cd6b86625
Create Date: 2026-07-20 14:15:20.963443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb9639cd5a3a'
down_revision: Union[str, None] = '2d5cd6b86625'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('knowledge_documents', sa.Column('grammar_point_id', sa.UUID(), nullable=True))
    op.alter_column('knowledge_documents', 'unit_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_unique_constraint('uq_knowledge_document_grammar_point_file', 'knowledge_documents', ['grammar_point_id', 'file_name'])
    op.create_foreign_key(None, 'knowledge_documents', 'grammar_points', ['grammar_point_id'], ['id'])
    # ### end Alembic commands ###
    # Bỏ qua thay đổi index/FK trên knowledge_chunks: autogenerate báo sai lệch do
    # SQLAlchemy không phản chiếu ondelete=CASCADE hiện có trong DB, không liên quan
    # tới thay đổi này — xem c2e6a1f9d3b4_add_knowledge_base.py cho định nghĩa gốc.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'knowledge_documents', type_='foreignkey')
    op.drop_constraint('uq_knowledge_document_grammar_point_file', 'knowledge_documents', type_='unique')
    op.alter_column('knowledge_documents', 'unit_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('knowledge_documents', 'grammar_point_id')
    # ### end Alembic commands ###
